// <auto-generated />
using EFGetStartedAgain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFGetStartedAgain.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("EFGetStartedAgain.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EFGetStartedAgain.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFGetStartedAgain.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskItemId");

                    b.HasIndex("TeamId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("EFGetStartedAgain.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("CurrentTaskId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EFGetStartedAgain.TeamWorker", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("TeamWorkers");
                });

            modelBuilder.Entity("EFGetStartedAgain.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TodoId");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("EFGetStartedAgain.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTodoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.HasIndex("CurrentTodoId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("EFGetStartedAgain.Post", b =>
                {
                    b.HasOne("EFGetStartedAgain.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EFGetStartedAgain.TaskItem", b =>
                {
                    b.HasOne("EFGetStartedAgain.Team", "Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EFGetStartedAgain.Team", b =>
                {
                    b.HasOne("EFGetStartedAgain.TaskItem", "CurrentTask")
                        .WithMany()
                        .HasForeignKey("CurrentTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("EFGetStartedAgain.TeamWorker", b =>
                {
                    b.HasOne("EFGetStartedAgain.Team", "Team")
                        .WithMany("TeamWorkers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFGetStartedAgain.Worker", "Worker")
                        .WithMany("TeamWorkers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EFGetStartedAgain.Todo", b =>
                {
                    b.HasOne("EFGetStartedAgain.TaskItem", "TaskItem")
                        .WithMany("Todos")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFGetStartedAgain.Worker", "Worker")
                        .WithMany("Todos")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("EFGetStartedAgain.Worker", b =>
                {
                    b.HasOne("EFGetStartedAgain.Todo", "CurrentTodo")
                        .WithMany()
                        .HasForeignKey("CurrentTodoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentTodo");
                });

            modelBuilder.Entity("EFGetStartedAgain.Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("EFGetStartedAgain.TaskItem", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("EFGetStartedAgain.Team", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("TeamWorkers");
                });

            modelBuilder.Entity("EFGetStartedAgain.Worker", b =>
                {
                    b.Navigation("TeamWorkers");

                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
